SCRIPTS=	reticen8.sh reticen8-import.sh reticen8-install.sh \
		reticen8-reset.sh reticen8-rootpass.sh reticen8-ufs.sh \
		reticen8-zfs.sh reticen8.subr.sh

MAN=		# not needed

PREFIX?=${DESTDIR}/usr

BINDIR=	${PREFIX}/libexec/bsdinstall

.include <bsd.prog.mk>
